#!/usr/bin/env ruby

require './init'

require 'thor'

class DoubleNegative::Runner < Thor
  desc 'copy-merge photos into archival folder', 'copy-merge photos into archival folder'

  def copy(source, dest)
    merge = DoubleNegative::Merge.new(source, dest)
    merge.plan.build
    merge.plan.check

    ap merge.plan.nodes

    merge.plan.execute
  end
end


DoubleNegative::Runner.start(ARGV)
